/**
 * Chat message schema (Phase 2, Milestone 1).
 *
 * Describes one message in a conversation held only in renderer memory —
 * nothing here is persisted to disk in this milestone. Every message,
 * regardless of role, is validated the same way: a message is untrusted input
 * the moment it did not originate from this module's own factory, whether it
 * came from a user's keystrokes or from a provider (mock today, real in a
 * later phase).
 *
 * Nothing here executes, interprets, or renders content as anything other
 * than plain text — see `src/renderer/chat/Chat.tsx`, which never uses
 * `dangerouslySetInnerHTML`.
 */

import { z } from 'zod';

import {
  BIDI_CONTROL_PATTERN,
  CHAT_CONTROL_CHARACTER_PATTERN,
  CHAT_CONVERSATION_MAX_MESSAGES,
  CHAT_MESSAGE_CONTENT_MAX_LENGTH,
  CHAT_MESSAGE_CONTENT_MIN_LENGTH,
  CHAT_MESSAGE_ROLES,
  CHAT_MESSAGE_STATUSES,
} from '../constants';
import { auditParametersSchema } from './audit-parameters.schema';
import type { AuditParameters } from './audit-parameters.schema';

/**
 * Bounded, control-character- and bidi-safe text, shared by a message's own
 * `content` and by {@link chatProviderResultSchema}'s `content` — the same
 * safety rules apply the moment either crosses a validation boundary,
 * whether that text was typed by the user or returned by a provider.
 */
const chatContentSchema = z
  .string()
  .min(CHAT_MESSAGE_CONTENT_MIN_LENGTH)
  .max(CHAT_MESSAGE_CONTENT_MAX_LENGTH)
  .refine((value) => !CHAT_CONTROL_CHARACTER_PATTERN.test(value), {
    message: 'must not contain unsafe control characters',
  })
  .refine((value) => !BIDI_CONTROL_PATTERN.test(value), {
    message: 'must not contain bidirectional control characters',
  });

/**
 * Reuses the audit-parameter schema for message metadata rather than
 * defining a second bounded-JSON-object schema: the requirements are
 * identical — plain JSON values only, bounded depth/breadth/size, and any
 * secret-looking field name rejected unless its value is already the
 * redaction placeholder. A message's `metadata` can therefore never carry a
 * credential under a name such as `apiKey` or `token`, enforced the same way
 * an audit record already is.
 */
export const chatMessageMetadataSchema = auditParametersSchema;
export type ChatMessageMetadata = AuditParameters;

export const chatMessageSchema = z.strictObject({
  /** Stable, caller-supplied identifier — a UUID generated by the renderer. */
  id: z.uuid(),
  role: z.enum(CHAT_MESSAGE_ROLES),
  content: chatContentSchema,
  /** UTC ISO-8601. Offsets are rejected so every message is comparable and sortable. */
  createdAt: z.iso.datetime(),
  /** See {@link CHAT_MESSAGE_STATUSES}'s doc comment for why this is unused today. */
  status: z.enum(CHAT_MESSAGE_STATUSES).optional(),
  /** Bounded, JSON-safe, never a credential — see {@link chatMessageMetadataSchema}. */
  metadata: chatMessageMetadataSchema.optional(),
});

export type ChatMessage = z.infer<typeof chatMessageSchema>;

/**
 * Validates and constructs one message.
 *
 * Every field the caller cannot vouch for as already-safe (`content`, and
 * `metadata` if supplied) is untrusted input, so this always runs the full
 * schema rather than trusting the shape of its argument. Throws a
 * `z.ZodError` on invalid input — callers (see
 * `src/renderer/chat/conversation-controller.ts`) catch it and turn it into
 * conversation-level error state rather than letting it propagate as an
 * unhandled exception.
 */
export function createChatMessage(input: {
  readonly id: string;
  readonly role: (typeof CHAT_MESSAGE_ROLES)[number];
  readonly content: string;
  readonly createdAt: string;
  readonly status?: (typeof CHAT_MESSAGE_STATUSES)[number];
  readonly metadata?: ChatMessageMetadata;
}): ChatMessage {
  return chatMessageSchema.parse(input);
}

/**
 * A `ChatProvider.send()` request, validated at the boundary where a
 * conversation crosses into a provider (Phase 2, Milestone 2).
 *
 * Every message it carries was already constructed through
 * {@link createChatMessage}, so this mainly re-asserts one property that,
 * before this milestone, was enforced only by `ConversationController`'s own
 * runtime `if` check and nowhere in the schema layer: the conversation
 * cannot exceed {@link CHAT_CONVERSATION_MAX_MESSAGES}. `strictObject` also
 * means a request cannot carry an extra field (a stray `apiKey`, say)
 * without being rejected outright.
 */
export const chatProviderRequestSchema = z.strictObject({
  messages: z.array(chatMessageSchema).max(CHAT_CONVERSATION_MAX_MESSAGES),
});
export type ChatProviderRequestPayload = z.infer<typeof chatProviderRequestSchema>;

/**
 * A `ChatProvider.send()` result, validated the moment it comes back from
 * a provider — mock today, real in a later phase — and before its `content`
 * is trusted for anything, including being wrapped into a
 * {@link ChatMessage} by `createChatMessage`. Rejects a non-string, an empty,
 * an oversized, or an unsafe `content`, and — via `strictObject` — any field
 * beyond `content` at all, so a provider cannot smuggle extra data (a
 * "confidence score," a raw upstream error object, anything) past this
 * boundary.
 */
export const chatProviderResultSchema = z.strictObject({
  content: chatContentSchema,
});
export type ChatProviderResultPayload = z.infer<typeof chatProviderResultSchema>;
