/**
 * Schemas for the controlled coding actions (Phase 2, Milestone 6).
 *
 * Milestone 5's `workspace.schema.ts` describes a workspace that can only be
 * read, and pins `codingPlanSchema.diff` to `null` so that stays true by
 * construction. This file is where a change becomes representable — and the
 * shape of it is where most of the milestone's safety lives, so three
 * properties are stated before the code:
 *
 *  - **A change is proposed once and applied by reference.** The renderer
 *    sends file content to {@link workspaceEditSchema} exactly once, when
 *    asking for a diff. Applying is
 *    {@link workspaceChangeIdSchema} and nothing else — no path, no content,
 *    no destination. So the bytes written are necessarily the bytes that were
 *    diffed and shown; there is no second opportunity to substitute them, and
 *    a compromised renderer cannot show one change and commit another.
 *  - **No schema here can express a destination.** Every path is
 *    project-relative and validated by the same
 *    `isSafeWorkspaceRelativePath` rule Milestone 5 established, so an
 *    absolute path, a `..` segment, a drive letter or an NTFS stream name
 *    cannot be represented at all. There is no "create" and no "delete": a
 *    change modifies files that already exist.
 *  - **No schema here can express a command.** {@link commandIdSchema} is an
 *    enum of five identifiers. There is no field anywhere in this file for a
 *    command string, an argument, a shell, a working directory or an
 *    environment variable.
 *
 * Pure: no I/O, no Node built-in, no Electron.
 */

import { z } from 'zod';

import {
  BIDI_CONTROL_PATTERN,
  COMMAND_MAX_DISPLAY_LENGTH,
  COMMAND_MAX_OUTPUT_LINE_LENGTH,
  COMMAND_MAX_OUTPUT_LINES,
  COMMAND_SCRIPT_PREVIEW_MAX_LENGTH,
  CONTROL_CHARACTER_PATTERN,
  GIT_MAX_STATUS_ENTRIES,
  WORKSPACE_DIFF_MAX_LINE_LENGTH,
  WORKSPACE_DIFF_MAX_LINES,
  WORKSPACE_MAX_CHANGE_FILES,
  WORKSPACE_MAX_WRITE_BYTES,
  WORKSPACE_PLAN_MAX_TEXT_LENGTH,
} from '../constants';
import { CODING_COMMAND_IDS, SCRIPT_RISK_FLAGS } from '../workspace/command-registry';
import { DIFF_LINE_KINDS, DIFF_WARNINGS } from '../workspace/diff';
import { GIT_STATUS_STATES } from '../workspace/git';
import { workspaceEntryPathSchema, workspaceNameSchema } from './workspace.schema';

// ---------------------------------------------------------------------------
// Shared primitives
// ---------------------------------------------------------------------------

/**
 * One line of rendered text crossing to the interface — a diff line, a line of
 * command output, a line of `git diff`.
 *
 * Control characters and bidirectional overrides are refused rather than
 * warned about, because every producer in this codebase sanitizes before
 * building one. That makes this schema the *check* on the sanitizer rather
 * than a second implementation of it: if a producer ever stops sanitizing,
 * the response fails validation in the main process instead of reaching a
 * screen where it could misrepresent what is about to be written.
 */
function renderedLine(maxLength: number): z.ZodType<string> {
  return z
    .string()
    .max(maxLength)
    .refine((value) => !CONTROL_CHARACTER_PATTERN.test(value), {
      message: 'must not contain control characters',
    })
    .refine((value) => !BIDI_CONTROL_PATTERN.test(value), {
      message: 'must not contain bidirectional control characters',
    });
}

/**
 * Built from a code point rather than written as an escape sequence, so that
 * no literal NUL byte ever appears in this file's own source — the same
 * reason `main/workspace-inspector.ts` sanitizes with a character walk rather
 * than a regular expression.
 */
const NUL_CHARACTER = String.fromCharCode(0);

/** Identifies one change set. Generated by the main process, never by a caller. */
export const workspaceChangeIdSchema = z.uuid();

// ---------------------------------------------------------------------------
// Proposed edits
// ---------------------------------------------------------------------------

/**
 * The replacement text for one file.
 *
 * Bounded, and NUL is refused — the workspace only ever reads and writes text
 * it decoded as UTF-8, and a NUL means the caller is proposing something that
 * is not that. The byte length is checked separately in the main process,
 * because this bound is in UTF-16 code units and a multi-byte character
 * encodes to more bytes than it occupies here.
 */
export const workspaceProposedContentSchema = z
  .string()
  .max(WORKSPACE_MAX_WRITE_BYTES)
  .refine((value) => !value.includes(NUL_CHARACTER), { message: 'must not contain NUL' });

/** One file's proposed replacement. Modification only — never create, never delete. */
export const workspaceEditSchema = z.strictObject({
  path: workspaceEntryPathSchema,
  content: workspaceProposedContentSchema,
});

export type WorkspaceEdit = z.infer<typeof workspaceEditSchema>;

// ---------------------------------------------------------------------------
// Diffs
// ---------------------------------------------------------------------------

export const diffLineSchema = z.strictObject({
  kind: z.enum(DIFF_LINE_KINDS),
  text: renderedLine(WORKSPACE_DIFF_MAX_LINE_LENGTH),
});

export type DiffLineValue = z.infer<typeof diffLineSchema>;

export const diffHunkSchema = z.strictObject({
  oldStart: z.int().min(1),
  oldLines: z.int().min(0),
  newStart: z.int().min(1),
  newLines: z.int().min(0),
  lines: z.array(diffLineSchema).max(WORKSPACE_DIFF_MAX_LINES),
});

export const fileDiffSchema = z.strictObject({
  path: workspaceEntryPathSchema,
  name: workspaceNameSchema,
  hunks: z.array(diffHunkSchema).max(WORKSPACE_DIFF_MAX_LINES),
  added: z.int().min(0),
  removed: z.int().min(0),
  /** True when the differ reported one coarse replacement instead of aligning. */
  coarse: z.boolean(),
  truncated: z.boolean(),
  warnings: z.array(z.enum(DIFF_WARNINGS)).max(DIFF_WARNINGS.length),
});

export type FileDiffValue = z.infer<typeof fileDiffSchema>;

// ---------------------------------------------------------------------------
// Change sets
// ---------------------------------------------------------------------------

/**
 * `'awaiting-approval'` is the only status a newly proposed change set can
 * have, and the only one from which it can be applied. There is deliberately
 * no `'approved'`: approval is not a property a change set carries around, it
 * is a native confirmation answered at the moment of writing.
 */
export const WORKSPACE_CHANGE_STATUSES = [
  'awaiting-approval',
  'applied',
  'rolled-back',
  'failed',
] as const;

export const workspaceChangeSetSchema = z.strictObject({
  id: workspaceChangeIdSchema,
  createdAt: z.iso.datetime(),
  status: z.enum(WORKSPACE_CHANGE_STATUSES),
  files: z.array(fileDiffSchema).max(WORKSPACE_MAX_CHANGE_FILES),
  totalAdded: z.int().min(0),
  totalRemoved: z.int().min(0),
  /** True when the diff budget stopped before every file was fully described. */
  truncated: z.boolean(),
  /**
   * Pinned to `true`. There is no shape in which a change set arrives already
   * approved, and no field a caller could set to skip the confirmation.
   */
  approvalRequired: z.literal(true),
  /** True once a backup exists, which is what makes rollback possible. */
  backupAvailable: z.boolean(),
  appliedAt: z.iso.datetime().nullable(),
  rolledBackAt: z.iso.datetime().nullable(),
});

export type WorkspaceChangeSet = z.infer<typeof workspaceChangeSetSchema>;

/** The session's change history, newest first. */
export const workspaceChangeHistorySchema = z.strictObject({
  changes: z.array(workspaceChangeSetSchema).max(64),
  /** The id of the most recent applied change, which rollback would restore. */
  rollbackTarget: workspaceChangeIdSchema.nullable(),
});

export type WorkspaceChangeHistory = z.infer<typeof workspaceChangeHistorySchema>;

// ---------------------------------------------------------------------------
// Commands
// ---------------------------------------------------------------------------

export const commandIdSchema = z.enum(CODING_COMMAND_IDS);

export type CommandIdValue = z.infer<typeof commandIdSchema>;

export const commandDescriptorSchema = z.strictObject({
  id: commandIdSchema,
  /** Fixed interface text from the registry, never from the project. */
  label: z.string().min(1).max(WORKSPACE_PLAN_MAX_TEXT_LENGTH),
  description: z.string().min(1).max(WORKSPACE_PLAN_MAX_TEXT_LENGTH),
  /** `npm run test`. Built from literals in the registry. */
  commandLine: renderedLine(COMMAND_MAX_DISPLAY_LENGTH),
  /** False when the project does not declare the script this would run. */
  available: z.boolean(),
  /**
   * The project's own script text, sanitized to a single bounded line. `null`
   * when the project declares no such script. Untrusted content: it is shown
   * so the user can see what they are approving, never parsed or acted on.
   */
  scriptPreview: renderedLine(COMMAND_SCRIPT_PREVIEW_MAX_LENGTH).nullable(),
  risks: z.array(z.enum(SCRIPT_RISK_FLAGS)).max(SCRIPT_RISK_FLAGS.length),
});

export type CommandDescriptor = z.infer<typeof commandDescriptorSchema>;

export const commandCatalogSchema = z.strictObject({
  commands: z.array(commandDescriptorSchema).max(CODING_COMMAND_IDS.length),
  /** True when a command is running right now, so a second may not start. */
  busy: z.boolean(),
});

export type CommandCatalog = z.infer<typeof commandCatalogSchema>;

export const COMMAND_OUTPUT_STREAMS = ['stdout', 'stderr'] as const;

export const commandOutputLineSchema = z.strictObject({
  stream: z.enum(COMMAND_OUTPUT_STREAMS),
  text: renderedLine(COMMAND_MAX_OUTPUT_LINE_LENGTH),
});

export type CommandOutputLine = z.infer<typeof commandOutputLineSchema>;

/**
 * How a command finished.
 *
 * `'stopped'` covers a kill this application performed for its own reasons —
 * a timeout, a cancellation, or the emergency stop being engaged mid-run —
 * and is kept distinct from `'failed'` so the interface never tells a user
 * their tests failed when in fact the run was cut short.
 */
export const COMMAND_OUTCOMES = ['succeeded', 'failed', 'stopped'] as const;

export const commandRunResultSchema = z.strictObject({
  runId: z.uuid(),
  commandId: commandIdSchema,
  commandLine: renderedLine(COMMAND_MAX_DISPLAY_LENGTH),
  outcome: z.enum(COMMAND_OUTCOMES),
  /** `null` when the process was killed rather than exiting on its own. */
  exitCode: z.int().min(-1).max(255).nullable(),
  startedAt: z.iso.datetime(),
  finishedAt: z.iso.datetime(),
  durationMs: z.int().min(0),
  output: z.array(commandOutputLineSchema).max(COMMAND_MAX_OUTPUT_LINES),
  /** True when an output bound stopped the capture before the command ended. */
  outputTruncated: z.boolean(),
  timedOut: z.boolean(),
  cancelled: z.boolean(),
  /** True when the emergency stop killed a command that was already running. */
  stoppedByEmergency: z.boolean(),
});

export type CommandRunResult = z.infer<typeof commandRunResultSchema>;

// ---------------------------------------------------------------------------
// Git
// ---------------------------------------------------------------------------

export const gitStatusEntrySchema = z.strictObject({
  path: workspaceEntryPathSchema,
  /** The two porcelain characters, kept verbatim for a reader who knows them. */
  code: z.string().length(2),
  state: z.enum(GIT_STATUS_STATES),
  staged: z.boolean(),
});

export type GitStatusEntryValue = z.infer<typeof gitStatusEntrySchema>;

export const gitStatusSchema = z.strictObject({
  /** `null` when HEAD is detached — a state a checkpoint is refused in. */
  branch: workspaceNameSchema.nullable(),
  entries: z.array(gitStatusEntrySchema).max(GIT_MAX_STATUS_ENTRIES),
  clean: z.boolean(),
  truncated: z.boolean(),
  /** Entries dropped because their path could not be represented safely. */
  unparsableEntries: z.int().min(0),
});

export type GitStatusValue = z.infer<typeof gitStatusSchema>;

export const GIT_DIFF_LINE_KINDS = ['meta', 'hunk', 'added', 'removed', 'context'] as const;

export const gitDiffLineSchema = z.strictObject({
  kind: z.enum(GIT_DIFF_LINE_KINDS),
  text: renderedLine(WORKSPACE_DIFF_MAX_LINE_LENGTH),
});

export const gitDiffSchema = z.strictObject({
  /** The single path this diff was narrowed to, or `null` for the whole tree. */
  path: workspaceEntryPathSchema.nullable(),
  lines: z.array(gitDiffLineSchema).max(WORKSPACE_DIFF_MAX_LINES),
  truncated: z.boolean(),
  /** True when git reported no difference at all. */
  empty: z.boolean(),
});

export type GitDiffValue = z.infer<typeof gitDiffSchema>;

export const gitCheckpointSchema = z.strictObject({
  branch: workspaceNameSchema,
  /** The short hash of the commit that was created. */
  commit: z.string().regex(/^[0-9a-f]{4,40}$/),
  /** The message the main process generated. Never renderer or project text. */
  message: renderedLine(WORKSPACE_PLAN_MAX_TEXT_LENGTH),
  filesChanged: z.int().min(0),
  createdAt: z.iso.datetime(),
});

export type GitCheckpointValue = z.infer<typeof gitCheckpointSchema>;
